blank_issues_enabled: false
contact_links:
  - name: LinkedIn
    url: https://www.linkedin.com/in/benjamin-cohen-082aa8a5/
    about: Please contact me on LinkedIn with questions or opportunities!
  - name: Kaggle
    url: https://www.kaggle.com/mrdragonbishop
    about: You can find my datasets on Kaggle.
